version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.09
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      - run:
          name: Build and Test
          command: ./gradlew build test

workflows:
  version: 2
  build:
    jobs:
      - build